[package]
name = "leptos-portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.15", features = ["csr"] }
leptos-use = "0.18.0"
utf16string = "0.2.0"
